import type { Locale } from "@/i18n/locales";
import type { Scenario } from "./hero-scenarios";

// Provenance (reviewed 2026-10-01): task choices draw on docs/seo-audits/2026-08-28-product-research-prd-knowledge-base-candidate.md, https://get.mem.ai/use-cases/meetings, and https://www.notion.com/use-case/project-management/product-backlog. These guide the task choice; the excerpts below are illustrative fixtures, not actual customer results.
// AI-product scenario direction (2026-10-03): https://www.anthropic.com/research/trustworthy-agents . Interview excerpts remain illustrative, not findings attributed to that research.
export const extraScenarios: Record<Locale, readonly Scenario[]> = {
  en: [
    {
      id: "writing",
      tabLabel: "Writing",
      title: "Newsletter editorial guidance",
      knowledgeSummary: {
        outcome: "Three example notes, one clear writing direction.",
        facts: [
          { label: "Style", value: "Plain language; no hype.", sources: [1] },
          { label: "Example", value: "Include one practical example.", sources: [2] },
          { label: "Open", value: "The next topic is undecided.", sources: [3] },
        ],
        nextUpdate: "Next update: add the topic once it is chosen.",
      },
      sourceContext: "Illustrative editorial notes for a sample newsletter.",
      capturedLabel: "Previously",
      captured: "Earlier editorial notes set a plain-language tone and call for a practical example.",
      questionLabel: "This time",
      question: "What style should I keep for this newsletter?",
      nextStepLabel: "Build on it",
      nextStep: "Use plain language and add one practical example. Avoid hype; the topic is still undecided.",
      sentenceSources: [[1, 2], [1, 3]],
      sourcesLabel: "View example records",
      sourcesHint: "Expand to read the illustrative excerpts",
      sources: [
        {
          id: "editorial-decisions",
          label: "editorial-decisions.md",
          detail: "Sample style decision",
          excerpt: "Use plain language and avoid promotional claims.",
          excerptLabel: "Example record",
        },
        {
          id: "newsletter-guide",
          label: "newsletter-guide.md",
          detail: "Sample newsletter guidance",
          excerpt: "Include one practical example readers can apply.",
          excerptLabel: "Example record",
        },
        {
          id: "draft-review",
          label: "draft-review.md",
          detail: "Sample open question",
          excerpt: "The next newsletter topic is still undecided.",
          excerptLabel: "Example record",
        },
      ],
    },
    {
      id: "meetings",
      tabLabel: "Meetings",
      title: "Prepare for the next meeting",
      knowledgeSummary: {
        outcome: "Three illustrative records, one budget check before the launch date.",
        facts: [
          { label: "Launch", value: "Launch moved to October.", sources: [1] },
          { label: "Budget", value: "Quote received; budget not approved.", sources: [2] },
          { label: "Next step", value: "Confirm budget, then settle the launch date.", sources: [3] },
        ],
        nextUpdate: "Next update: record the date after the budget is confirmed.",
      },
      sourceContext: "From meeting notes, follow-ups and a saved AI discussion.",
      capturedLabel: "Previously",
      captured: "Meeting notes moved launch to October; a later follow-up says the hosting quote arrived, but the budget remains unapproved.",
      questionLabel: "This time",
      question: "Before tomorrow's meeting, what is still unconfirmed?",
      nextStepLabel: "Build on it",
      nextStep: "Confirm the hosting budget first, then set the October launch date. The quote arrived, but the budget is still unapproved.",
      sentenceSources: [[1, 3], [2]],
      sourcesLabel: "View example records",
      sourcesHint: "Expand to read the illustrative excerpts",
      sources: [
        {
          id: "meeting-notes",
          label: "meeting-notes.md",
          detail: "Meeting note",
          excerpt: "The launch moved to October; hosting budget confirmation is still pending.",
          excerptLabel: "Example record",
        },
        {
          id: "follow-up",
          label: "follow-up.md",
          detail: "Budget follow-up",
          excerpt: "We received the hosting quote, but the budget is still unapproved.",
          excerptLabel: "Example record",
        },
        {
          id: "ai-discussion",
          label: "ai-discussion.md",
          detail: "Saved meeting prep",
          excerpt: "For the next meeting, confirm the hosting budget first, then choose the launch date.",
          excerptLabel: "Example record",
        },
      ],
    },
    {
      id: "product",
      tabLabel: "Product",
      title: "AI assistant product research",
      knowledgeSummary: {
        outcome: "Turn interview findings and a prior discussion into test directions for the next release.",
        facts: [
          { label: "Interview findings", value: "Review before sending; trace changes afterward.", sources: [1, 2] },
          { label: "Prior discussion", value: "Test a send preview and change history.", sources: [3] },
          { label: "To validate", value: "Will this make users more willing to delegate?", sources: [3] },
        ],
        nextUpdate: "Next update: add test results, then decide whether to adopt.",
      },
      sourceContext: "Example page: past interviews and a product discussion.",
      capturedLabel: "Previously",
      captured: "One interview asks to review emails before sending; another asks to see file changes. The design discussion proposes testing both controls.",
      questionLabel: "This time",
      question: "Based on past interviews, what should we improve in our AI assistant next?",
      nextStepLabel: "Build on it",
      nextStep: "Interviewees want to review emails before sending and trace file changes. Build on the prior discussion: test a send preview and change history; the benefit is still untested.",
      sentenceSources: [[1, 2], [3]],
      sourcesLabel: "View example records",
      sourcesHint: "Expand to read the illustrative excerpts",
      sources: [
        {
          id: "interview-01",
          label: "interview-01.md",
          detail: "AI assistant interview",
          excerpt: "I let the AI draft emails, but I want to see the recipient and message before it sends anything.",
          excerptLabel: "Example record",
        },
        {
          id: "interview-02",
          label: "interview-02.md",
          detail: "AI assistant interview",
          excerpt: "After the AI organizes my files, I cannot tell which files it changed, so I check them myself.",
          excerptLabel: "Example record",
        },
        {
          id: "product-review",
          label: "product-review.md",
          detail: "Product review",
          excerpt: "Test a recipient and message preview before sending, plus a history of file changes. Whether users will delegate more remains untested.",
          excerptLabel: "Example record",
        },
      ],
    },
  ],
  "zh-TW": [
    {
      id: "writing",
      tabLabel: "寫作",
      title: "電子報編輯方向",
      knowledgeSummary: {
        outcome: "三則示意紀錄，整理出清楚的寫作方向。",
        facts: [
          { label: "語氣", value: "使用白話，避免宣傳口吻。", sources: [1] },
          { label: "例子", value: "加入一個實用例子。", sources: [2] },
          { label: "未定", value: "下一期主題尚未決定。", sources: [3] },
        ],
        nextUpdate: "下一步：主題確定後再補上。",
      },
      sourceContext: "電子報寫作的示意編輯紀錄。",
      capturedLabel: "先前紀錄",
      captured: "先前的編輯紀錄要求使用白話，並加入實用例子。",
      questionLabel: "這次",
      question: "這期電子報，沿用什麼寫法？",
      nextStepLabel: "接續整理",
      nextStep: "沿用白話並加入實用例子。避免宣傳口吻；主題尚未決定。",
      sentenceSources: [[1, 2], [1, 3]],
      sourcesLabel: "查看示意紀錄",
      sourcesHint: "展開閱讀示意摘錄",
      sources: [
        {
          id: "editorial-decisions",
          label: "editorial-decisions.md",
          detail: "示意語氣決策",
          excerpt: "使用白話，避免宣傳口吻。",
          excerptLabel: "示意紀錄",
        },
        {
          id: "newsletter-guide",
          label: "newsletter-guide.md",
          detail: "示意電子報指南",
          excerpt: "加入一個讀者可以實際運用的例子。",
          excerptLabel: "示意紀錄",
        },
        {
          id: "draft-review",
          label: "draft-review.md",
          detail: "示意待確認事項",
          excerpt: "下一期電子報的主題尚未決定。",
          excerptLabel: "示意紀錄",
        },
      ],
    },
    {
      id: "meetings",
      tabLabel: "會議",
      title: "下次會議準備",
      knowledgeSummary: {
        outcome: "三則示意紀錄，先確認預算再敲定上線日期。",
        facts: [
          { label: "時程", value: "上線延到十月。", sources: [1] },
          { label: "預算", value: "報價已收到，預算未核准。", sources: [2] },
          { label: "下一步", value: "先確認預算，再敲定上線日期。", sources: [3] },
        ],
        nextUpdate: "下一步：預算確認後，再記下上線日期。",
      },
      sourceContext: "整理自：會議筆記、追蹤紀錄與 AI 對話。",
      capturedLabel: "先前紀錄",
      captured: "會議紀錄提到上線延到十月；後續追蹤已收到主機報價，但預算仍未核准。",
      questionLabel: "這次",
      question: "明天又要開會，上次哪些事還沒確認？",
      nextStepLabel: "接續整理",
      nextStep: "先確認主機預算，再敲定十月上線日。報價已收到，但預算還沒核准。",
      sentenceSources: [[1, 3], [2]],
      sourcesLabel: "查看示意紀錄",
      sourcesHint: "展開閱讀示意摘錄",
      sources: [
        {
          id: "meeting-notes",
          label: "meeting-notes.md",
          detail: "會議紀錄",
          excerpt: "上線延到十月；主機預算仍待確認。",
          excerptLabel: "示意紀錄",
        },
        {
          id: "follow-up",
          label: "follow-up.md",
          detail: "預算後續追蹤",
          excerpt: "已收到主機報價，但預算尚未核准。",
          excerptLabel: "示意紀錄",
        },
        {
          id: "ai-discussion",
          label: "ai-discussion.md",
          detail: "已儲存的會議準備討論",
          excerpt: "下次會議先確認主機預算，再決定上線日期。",
          excerptLabel: "示意紀錄",
        },
      ],
    },
    {
      id: "product",
      tabLabel: "產品",
      title: "AI 助理產品研究",
      knowledgeSummary: {
        outcome: "把訪談發現與上次討論，整理成下一版的測試方向。",
        facts: [
          { label: "訪談發現", value: "寄信前要確認，改檔後要追查。", sources: [1, 2] },
          { label: "上次討論", value: "先試寄送預覽與變更紀錄。", sources: [3] },
          { label: "待驗證", value: "是否讓使用者更願意交辦。", sources: [3] },
        ],
        nextUpdate: "下次更新：補入測試結果，再決定是否採用。",
      },
      sourceContext: "示意：先前訪談與產品討論整理成的知識頁。",
      capturedLabel: "先前紀錄",
      captured: "一份訪談希望寄信前先確認，另一份想知道 AI 改了哪些檔案；設計討論提出寄送預覽與變更紀錄，效果仍待測試。",
      questionLabel: "這次",
      question: "根據之前的訪談，我們的 AI 助理下一版該先改什麼？",
      nextStepLabel: "接續整理",
      nextStep: "訪談指出，使用者需要寄出前確認、改完後追查。接續上次討論，先測試寄送預覽與檔案變更紀錄，效果仍待驗證。",
      sentenceSources: [[1, 2], [3]],
      sourcesLabel: "查看示意紀錄",
      sourcesHint: "展開閱讀示意摘錄",
      sources: [
        {
          id: "interview-01",
          label: "interview-01.md",
          detail: "AI 助理使用者訪談",
          excerpt: "我會讓 AI 寫信，但寄出前要先看收件人和內容，才敢交給它。",
          excerptLabel: "示意紀錄",
        },
        {
          id: "interview-02",
          label: "interview-02.md",
          detail: "AI 助理使用者訪談",
          excerpt: "AI 整理完檔案後，我不知道它改了哪些，還是得自己一個個檢查。",
          excerptLabel: "示意紀錄",
        },
        {
          id: "product-review",
          label: "product-review.md",
          detail: "產品檢視",
          excerpt: "先測試寄出前預覽收件人與內容，以及操作後的檔案變更紀錄；是否增加交辦意願仍待驗證。",
          excerptLabel: "示意紀錄",
        },
      ],
    },
  ],
  "zh-CN": [
    {
      id: "writing",
      tabLabel: "写作",
      title: "电子报编辑方向",
      knowledgeSummary: {
        outcome: "三条示例记录，整理出清晰的写作方向。",
        facts: [
          { label: "语气", value: "使用白话，避免宣传语气。", sources: [1] },
          { label: "例子", value: "加入一个实用例子。", sources: [2] },
          { label: "待定", value: "下一期主题尚未确定。", sources: [3] },
        ],
        nextUpdate: "下一步：主题确定后再补充。",
      },
      sourceContext: "电子报写作的示例编辑记录。",
      capturedLabel: "先前记录",
      captured: "先前的编辑记录要求使用白话，并加入实用例子。",
      questionLabel: "这次",
      question: "这期电子报，沿用什么写法？",
      nextStepLabel: "接续整理",
      nextStep: "沿用白话并加入实用例子。避免宣传语气；主题尚未确定。",
      sentenceSources: [[1, 2], [1, 3]],
      sourcesLabel: "查看示例记录",
      sourcesHint: "展开阅读示例摘录",
      sources: [
        {
          id: "editorial-decisions",
          label: "editorial-decisions.md",
          detail: "示例语气决策",
          excerpt: "使用白话，避免宣传语气。",
          excerptLabel: "示例记录",
        },
        {
          id: "newsletter-guide",
          label: "newsletter-guide.md",
          detail: "示例电子报指南",
          excerpt: "加入一个读者可以实际运用的例子。",
          excerptLabel: "示例记录",
        },
        {
          id: "draft-review",
          label: "draft-review.md",
          detail: "示例待确认事项",
          excerpt: "下一期电子报的主题尚未确定。",
          excerptLabel: "示例记录",
        },
      ],
    },
    {
      id: "meetings",
      tabLabel: "会议",
      title: "下次会议准备",
      knowledgeSummary: {
        outcome: "三条示例记录，先确认预算再敲定上线日期。",
        facts: [
          { label: "进度", value: "上线推迟到十月。", sources: [1] },
          { label: "预算", value: "报价已收到，预算未获批准。", sources: [2] },
          { label: "下一步", value: "先确认预算，再敲定上线日期。", sources: [3] },
        ],
        nextUpdate: "下一步：预算确认后，再记录上线日期。",
      },
      sourceContext: "整理自：会议笔记、跟进记录与 AI 对话。",
      capturedLabel: "先前记录",
      captured: "会议记录提到上线推迟到十月；后续跟进已收到主机报价，但预算仍未获批准。",
      questionLabel: "这次",
      question: "明天又要开会，上次还有哪些事没确认？",
      nextStepLabel: "接续整理",
      nextStep: "先确认主机预算，再敲定十月上线日期。报价已收到，但预算尚未批准。",
      sentenceSources: [[1, 3], [2]],
      sourcesLabel: "查看示例记录",
      sourcesHint: "展开阅读示例摘录",
      sources: [
        {
          id: "meeting-notes",
          label: "meeting-notes.md",
          detail: "会议记录",
          excerpt: "上线推迟到十月；主机预算仍待确认。",
          excerptLabel: "示例记录",
        },
        {
          id: "follow-up",
          label: "follow-up.md",
          detail: "预算后续跟进",
          excerpt: "已收到主机报价，但预算尚未获批准。",
          excerptLabel: "示例记录",
        },
        {
          id: "ai-discussion",
          label: "ai-discussion.md",
          detail: "已保存的会议准备讨论",
          excerpt: "下次会议先确认主机预算，再决定上线日期。",
          excerptLabel: "示例记录",
        },
      ],
    },
    {
      id: "product",
      tabLabel: "产品",
      title: "AI 助理产品研究",
      knowledgeSummary: {
        outcome: "将访谈发现和上次讨论，整理成下一版的测试方向。",
        facts: [
          { label: "访谈发现", value: "发邮件前要确认，改文件后要追踪。", sources: [1, 2] },
          { label: "上次讨论", value: "先试发送预览与变更记录。", sources: [3] },
          { label: "待验证", value: "是否让用户更愿意交办。", sources: [3] },
        ],
        nextUpdate: "下次更新：补入测试结果，再决定是否采用。",
      },
      sourceContext: "示例：由先前访谈与产品讨论整理而成的知识页。",
      capturedLabel: "先前记录",
      captured: "一份访谈希望发邮件前先确认，另一份想知道 AI 改了哪些文件；设计讨论提出发送预览与变更记录，效果仍待测试。",
      questionLabel: "这次",
      question: "根据之前的访谈，我们的 AI 助理下一版应该先改进什么？",
      nextStepLabel: "接续整理",
      nextStep: "访谈指出，用户需要发送前确认、改完后追踪。接续上次讨论，先测试发送预览与文件变更记录，效果仍待验证。",
      sentenceSources: [[1, 2], [3]],
      sourcesLabel: "查看示例记录",
      sourcesHint: "展开阅读示例摘录",
      sources: [
        {
          id: "interview-01",
          label: "interview-01.md",
          detail: "AI 助理用户访谈",
          excerpt: "我会让 AI 写邮件，但发出前要先看收件人和内容，才敢交给它。",
          excerptLabel: "示例记录",
        },
        {
          id: "interview-02",
          label: "interview-02.md",
          detail: "AI 助理用户访谈",
          excerpt: "AI 整理完文件后，我不知道它改了哪些，还是得自己逐个检查。",
          excerptLabel: "示例记录",
        },
        {
          id: "product-review",
          label: "product-review.md",
          detail: "产品评审",
          excerpt: "先测试发送前预览收件人和内容，以及操作后的文件变更记录；是否增加交办意愿仍待验证。",
          excerptLabel: "示例记录",
        },
      ],
    },
  ],
};

export const extraAnswerHighlights: Record<
  Locale,
  Record<"writing" | "meetings" | "product", readonly string[]>
> = {
  en: {
    writing: ["plain language"],
    meetings: ["Confirm the hosting budget", "budget is still unapproved"],
    product: ["review emails before sending", "trace file changes"],
  },
  "zh-TW": {
    writing: ["白話"],
    meetings: ["先確認主機預算", "預算還沒核准"],
    product: ["寄出前確認", "改完後追查"],
  },
  "zh-CN": {
    writing: ["白话"],
    meetings: ["先确认主机预算", "预算尚未批准"],
    product: ["发送前确认", "改完后追踪"],
  },
};
